# Generated by Django 4.0.4 on 2022-06-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='foto',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
